From centos
Maintainer "Elavarasan"
Run yum update -y
Run yum install httpd -y
Run  yum install epel-release yum-utils
Run yum install php
Run systemctl restart httpd
CMD "catalina.sh" "run"
EXPOSE 8080

