From centos
Maintainer "Elavarasan"
Run yum update -y
Run yum install httpd -y
Run yum install epel-release yum-utils -y
Run yum install php -y 
#Run systemctl start httpd
CMD "catalina.sh" "run"
EXPOSE 80

